"""Stage J followup-2 Gate 1 — legacy invariance after coupling refactor.

The mechanical-step kernel ``models.diesel_coupling`` replaces the
inline ``for k in range(N_SUB):`` corrector body in
``models.diesel_transient.run_transient`` (followup-2 Step 4). For
the legacy half-Sommerfeld + dimple path the move MUST be bit-for-
bit equivalent to the pre-refactor runner — Gate 1 of the followup-2
plan. This test pins that equivalence against a real-GPU npz fixture
captured immediately before the refactor landed.

Fixture
-------
``tests/fixtures/legacy_invariance_smoke_fmax050_fidelity_low.npz``
was generated by the user on the GPU box with::

    python scripts/run_diesel_thd_transient.py \\
        --mode global_relax --gamma 0.7 --tau-th 0.5 \\
        --cavitation half_sommerfeld --texture-kind dimple \\
        --F-max-scale 0.5 --fidelity low \\
        --configs mineral_smooth,mineral_textured \\
        --seed 0

Two configs:
    [0] mineral_smooth   — runs 583 / 583 steps (no abort)
    [1] mineral_textured — aborts at step 6 (clamp_frac_exceeded)
                           — pre-existing failure mode at fidelity=low
                           with under-resolved h_p=30 µm dimples

Bidirectional contract
----------------------
Gate 1 catches drift in BOTH directions:

* If post-refactor mineral_smooth eps orbit drifts beyond 1e-6 from
  the fixture → solver coupling regression.
* If post-refactor mineral_textured runs **further** than step 6 →
  reverse regression (e.g. retry/clamp accounting changed).

Both require investigation; do not silently relax the tolerance.

Skipping
--------
Skipped cleanly without ``cupy`` / ``GPU_reynolds`` (the legacy
half-Sommerfeld path uses ``solve_reynolds`` from the GPU package
in production — the conftest stub raises rather than emulating the
pre-refactor results).
"""
from __future__ import annotations

import os

import numpy as np
import pytest


cupy = pytest.importorskip(
    "cupy",
    reason="Gate 1 needs cupy to run the real solve_reynolds path")
solve_reynolds_pkg = pytest.importorskip(
    "reynolds_solver",
    reason="Gate 1 needs reynolds_solver to reproduce the fixture")


from models.diesel_transient import (  # noqa: E402
    CONFIGS, EnvelopeAbortConfig, run_transient,
)
from models.thermal_coupling import ThermalConfig  # noqa: E402


_FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__),
    "fixtures",
    "legacy_invariance_smoke_fmax050_fidelity_low.npz",
)


# Op-order preserved by the bit-for-bit kernel move; SOR on GPU may
# still introduce float64 reduce-order noise, so we use the looser
# Gate 1 tolerance (1e-6 relative) on the orbit. Scalars must
# match exactly (integer counts, abort reason).
_ORBIT_REL_TOL = 1e-6
_T_EFF_ABS_TOL = 1e-3        # °C


@pytest.fixture(scope="module")
def fixture_npz():
    if not os.path.isfile(_FIXTURE_PATH):
        pytest.skip(
            f"Gate 1 fixture not present: {_FIXTURE_PATH}. "
            "Generate with the smoke command in the module docstring.")
    return np.load(_FIXTURE_PATH, allow_pickle=True)


@pytest.fixture(scope="module")
def post_refactor_results():
    """Re-run the smoke through the refactored runner.

    The kernel call replaces the inline ``for k in range(N_SUB):``
    body for the ``half_sommerfeld`` path; everything else is
    untouched (thermal coupling, retry policy, clamp accounting,
    envelope-abort gate).
    """
    thermal = ThermalConfig(
        mode="global_relax",
        T_in_C=105.0,
        gamma_mix=0.7,
        cp_J_kgK=2000.0,
        mdot_floor_kg_s=1e-4,
        tau_th_s=0.5,
    )
    return run_transient(
        F_max=0.5 * 850_000.0,
        configs=[CONFIGS[0], CONFIGS[2]],   # mineral_smooth, mineral_textured
        cavitation="half_sommerfeld",
        texture_kind="dimple",
        thermal=thermal,
        fidelity="low",
        n_grid=160,                         # fidelity=low default Nφ
        n_z_grid=60,                        # fidelity=low default Nz
        n_cycles=2,
        d_phi_base_deg=4.0,
        d_phi_peak_deg=1.0,
        envelope_abort=EnvelopeAbortConfig(),  # default thresholds
        seed=0,
    )


# ─── 1. mineral_smooth — full 583-step orbit equivalence ──────────


def test_mineral_smooth_eps_orbit_matches_fixture(
    fixture_npz, post_refactor_results):
    """The mineral_smooth orbit must reproduce the fixture within
    Gate 1 tolerance (1e-6 rel). ALL 583 accepted steps."""
    n_smooth = int(fixture_npz["steps_completed"][0])
    assert n_smooth == 583, (
        f"fixture says mineral_smooth completed {n_smooth} steps "
        "(expected 583)")
    eps_x_fix = fixture_npz["eps_x"][0, :n_smooth]
    eps_y_fix = fixture_npz["eps_y"][0, :n_smooth]
    eps_x_new = np.asarray(
        post_refactor_results["eps_x"])[0, :n_smooth]
    eps_y_new = np.asarray(
        post_refactor_results["eps_y"])[0, :n_smooth]
    np.testing.assert_allclose(
        eps_x_new, eps_x_fix,
        rtol=_ORBIT_REL_TOL, atol=_ORBIT_REL_TOL,
        err_msg="mineral_smooth eps_x orbit drifted post-refactor")
    np.testing.assert_allclose(
        eps_y_new, eps_y_fix,
        rtol=_ORBIT_REL_TOL, atol=_ORBIT_REL_TOL,
        err_msg="mineral_smooth eps_y orbit drifted post-refactor")


def test_mineral_smooth_envelope_scalars_exact_match(
    fixture_npz, post_refactor_results):
    """Integer counts (contact_clamp, solver_failed, retry_*) must
    match exactly — these are byte-counted not floating-point."""
    fix = fixture_npz
    new = post_refactor_results
    assert int(new["steps_completed"][0]) == int(fix["steps_completed"][0])
    assert int(new["contact_clamp_count"][0]) == int(
        fix["contact_clamp_count"][0])
    assert int(new["solver_failed_count"][0]) == int(
        fix["solver_failed_count"][0])
    assert int(new["retry_recovered_count"][0]) == int(
        fix["retry_recovered_count"][0])
    assert int(new["retry_exhausted_count"][0]) == int(
        fix["retry_exhausted_count"][0])
    assert bool(new["aborted"][0]) is False
    assert bool(np.asarray(fix["aborted"])[0]) is False


def test_mineral_smooth_T_eff_last_cycle_matches(
    fixture_npz, post_refactor_results):
    """Thermal global_relax target: T_eff last-cycle min / mean /
    max within 1e-3 °C."""
    sl = slice(int(fixture_npz["last_start"]),
               int(fixture_npz["last_start"])
               + int(fixture_npz["n_steps_per_cycle"]))
    T_fix = np.asarray(fixture_npz["T_eff"])[0, sl]
    T_fix = T_fix[np.isfinite(T_fix)]
    sl_new = slice(int(post_refactor_results["last_start"]),
                   int(post_refactor_results["last_start"])
                   + int(post_refactor_results["n_steps_per_cycle"]))
    T_new = np.asarray(post_refactor_results["T_eff"])[0, sl_new]
    T_new = T_new[np.isfinite(T_new)]
    assert T_fix.size > 0 and T_new.size > 0
    assert abs(T_new.min() - T_fix.min()) < _T_EFF_ABS_TOL
    assert abs(T_new.mean() - T_fix.mean()) < _T_EFF_ABS_TOL
    assert abs(T_new.max() - T_fix.max()) < _T_EFF_ABS_TOL


# ─── 2. mineral_textured — aborts at step 6, identical reason ─────


def test_mineral_textured_aborts_at_step_6(
    fixture_npz, post_refactor_results):
    """The pre-existing failure mode (under-resolved dimples at
    fidelity=low) must trigger the SAME abort at the SAME step
    after the refactor. If post-refactor textured runs further than
    step 6, that is a reverse regression (clamp / retry accounting
    changed) and Gate 1 must catch it."""
    assert bool(np.asarray(fixture_npz["aborted"])[1]) is True
    assert bool(post_refactor_results["aborted"][1]) is True
    assert int(post_refactor_results["steps_completed"][1]) == int(
        fixture_npz["steps_completed"][1])
    abort_reason_new = str(
        post_refactor_results["abort_reason"][1])
    assert abort_reason_new.startswith("clamp_frac_exceeded"), (
        f"abort_reason changed: {abort_reason_new!r}")


def test_mineral_textured_pre_abort_scalars_match(
    fixture_npz, post_refactor_results):
    """Per-config envelope counters at the abort point must match
    exactly (clamp / fail / retry counts are integer-valued and
    deterministic in the legacy path)."""
    fix = fixture_npz
    new = post_refactor_results
    assert int(new["contact_clamp_count"][1]) == int(
        fix["contact_clamp_count"][1])
    assert int(new["solver_failed_count"][1]) == int(
        fix["solver_failed_count"][1])
    assert int(new["retry_recovered_count"][1]) == int(
        fix["retry_recovered_count"][1])
    assert int(new["retry_exhausted_count"][1]) == int(
        fix["retry_exhausted_count"][1])


def test_mineral_textured_first_clamp_phi_matches(
    fixture_npz, post_refactor_results):
    """The first crank-angle where the orbit hit ``eps_max`` must
    match within numerical precision."""
    phi_fix = float(np.asarray(fixture_npz["first_clamp_phi"])[1])
    phi_new = float(post_refactor_results["first_clamp_phi"][1])
    assert abs(phi_new - phi_fix) < 1e-6, (
        f"first_clamp_phi changed: {phi_new} vs fixture {phi_fix}")


def test_mineral_textured_first_six_steps_orbit_matches(
    fixture_npz, post_refactor_results):
    """For the 6 steps mineral_textured DID complete, the eps orbit
    must reproduce the fixture within Gate 1 tolerance."""
    n = int(fixture_npz["steps_completed"][1])
    assert n == 6
    eps_x_fix = fixture_npz["eps_x"][1, :n]
    eps_y_fix = fixture_npz["eps_y"][1, :n]
    eps_x_new = np.asarray(post_refactor_results["eps_x"])[1, :n]
    eps_y_new = np.asarray(post_refactor_results["eps_y"])[1, :n]
    np.testing.assert_allclose(
        eps_x_new, eps_x_fix,
        rtol=_ORBIT_REL_TOL, atol=_ORBIT_REL_TOL,
        err_msg="mineral_textured pre-abort eps_x drifted")
    np.testing.assert_allclose(
        eps_y_new, eps_y_fix,
        rtol=_ORBIT_REL_TOL, atol=_ORBIT_REL_TOL,
        err_msg="mineral_textured pre-abort eps_y drifted")


# ─── 3. Run-level metadata — must reproduce the same shape/schema ─


def test_results_dict_carries_post_refactor_metadata(
    post_refactor_results):
    """Sanity that the kernel-pathed run still surfaces the same
    top-level fields the legacy npz writer expects (no schema drift)."""
    keys = set(post_refactor_results)
    required = {
        "eps_x", "eps_y", "hmin", "pmax", "f", "F_tr", "N_loss",
        "Fx_hyd", "Fy_hyd", "phi_crank_deg", "phi_last",
        "last_start", "n_steps_per_cycle",
        "T_eff", "T_eff_used", "T_target",
        "eta_eff", "P_loss", "Q", "mdot",
        "solver_success", "valid_dynamic", "valid_no_clamp",
        "contact_clamp", "contact_clamp_event_count",
        "retry_used", "retry_omega_used",
        "contact_clamp_count", "solver_failed_count",
        "retry_recovered_count", "retry_exhausted_count",
        "aborted", "abort_reason",
        "first_clamp_phi", "first_invalid_phi",
        "first_solver_failed_phi",
        "steps_attempted", "steps_completed",
        "applicable", "applicable_reason",
        "cavitation_model", "texture_kind", "groove_preset",
        "fidelity",
    }
    missing = required - keys
    assert not missing, f"post-refactor result dict missing: {missing}"
